- name: Installing nginx package
  hosts: Node1
  become: yes
  tasks:
  - name: Install nginx 
    ansible.builtin.package:
      name: nginx
      state: installed

  - name: Start nginx server
    ansible.builtin.service:
      name: nginx
      state: started
      enable: yes

