- name: Play level Variables
  hosts: local
  connection: local
  vars:
    COURSE: DevSecOps
    DURATION: 120 Days
    TRAINER: Siva
  tasks:
  - name: Printing course information
    ansible.builtin.debug:
      msg: "I am learning {{ COURSE }} in {{ DURATION }} with trainer {{ TRAINER }}"