- name: Task Level Variables
  hosts: local
  connection: local
  vars:
    COURSE: DevSecOps
    DURATION: 120 Days
    TRAINER: Siva
  tasks:
  - name: Printing Course information
    vars:
      COURSE: AWS
      DURATION: 60 Days
      TRAINER: Siva Kumar
    ansible.builtin.debug:
      msg: "I am learning {{ COURSE }} in {{ DURATION }} with trainer {{ TRAINER }}"

  - name: Printing Course information again to check whether variables will be accessed
    ansible.builtin.debug:
      msg: "I am learning {{ COURSE }} in {{ DURATION }} with trainer {{ TRAINER }}"