- name: Variables from file
  hosts: local
  connection: local
  vars_file:
    07-course.yaml
  tasks:
  - name: file variables
    ansible.builtin.debug:
      msg: "I am learning {{ COURSE }} in {{ DURATION }} with trainer {{ TRAINER }}"
