- name: Prompt variables
  hosts: local
  connection: local
  tasks:
  - name: Variables from Prompt
    Vars_prompt:
    - name: USERNAME
      prompt: Enter the USERNAME
      private: true

    - name: PASSWORD
      prompt: Enter the PASSWORD
      private: true

  ansible.builtin.debug:
    msg: Username is {{ USERNAME }} and Password is {{ PASSWORD }}
