- name: Prompt variables
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: Enter the USERNAME
    private: true

  - name: PASSWORD
    prompt: Enter the PASSWORD
    private: true

  tasks:
  - name: Print Username and Password
    ansible.builtin.debug:
      msg: "Username is {{ USERNAME }} and Password is {{ PASSWORD }}"
