- name: Variables Preference
  hosts: local
  connection: local
  vars:
    MESSAGE: Hello from play variables
  vars_files:
  - 07-course.yaml
  vars_prompt:
    - name: MESSAGE
      prompt: Enter your Message
      private: false
  tasks: 
  - name: Print Variables Preference
    vars:
      MESSAGE: Hello from task variables
    ansible.builtin.debug:
      msg: "{{ MESSAGE }}"
