- name: Conditions in Ansible
  hosts: local
  connection: local
  NUM: 56
  task:
  - name: Print the number if it is less than 100
    ansible.builtin.debug:
      msg: "{{ NUM }} is between 1 to 100"
    when: NUM <= 100

  - name: Print number if it is greater than 100
    ansible.builtin.debug:
      msg: "{{ NUM }} is greater than 100"
    when: NUM > 100
