- name: loop with packages
  hosts: Node1
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.package:
      msg: "{{ item }}"
    loop:
    - nginx
    - httpd
    - mysql
    - zip
