- name: Multiuse loop
  hosts: Node1
  become: yes
  tasks:
  - name: Installing and uninstalling packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - {name: 'mysql', state: 'present'}
    - {name: 'httpd', state: 'absent'}
    - {name: 'zip', state: 'absent'}
    - {name: 'nginx', state: 'absent'}