- name: Creating the user
  hosts: local
  connection: local
  tasks:
  - name: Check whether roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: create user if doesnot exist
    become: yes
    ansible.builtin.command: useradd roboshop
    when: output.rc != 0

  - name: Skip if user exist
    ansible.builtin.debug:
      msg: "User already exist"
    when: output.rc == 0